version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/npm-app/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "monthly"
#      interval: "daily"

  # Enable version updates for npm
  - package-ecosystem: "gradle"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/java-app/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "monthly"
#      interval: "daily"
